MACHINES = {
  :router1 => {
    :box_name => "ubuntu/bionic64",
    :vm_name => "router1",
    :net => [
      { type: 'private_network', ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", intnet: "r1-r2" },
      { type: 'private_network', ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", intnet: "r1-r3" },
      { type: 'private_network', ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", intnet: "net1" },
      { type: 'private_network', ip: '192.168.50.10', adapter: 5 }
    ]
  },

  :router2 => {
    :box_name => "ubuntu/bionic64",
    :vm_name => "router2",
    :net => [
      { type: 'private_network', ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", intnet: "r1-r2" },
      { type: 'private_network', ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", intnet: "r2-r3" },
      { type: 'private_network', ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", intnet: "net2" },
      { type: 'private_network', ip: '192.168.50.11', adapter: 5 }
    ]
  },

  :router3 => {
    :box_name => "ubuntu/bionic64",
    :vm_name => "router3",
    :net => [
      { type: 'private_network', ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", intnet: "r2-r3" },
      { type: 'private_network', ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", intnet: "r1-r3" },
      { type: 'private_network', ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", intnet: "net3" },
      { type: 'private_network', ip: '192.168.50.12', adapter: 5 }
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      boxconfig[:net].each do |ipconf|
        # Настраиваем сеть для каждой машины
        box.vm.network ipconf[:type], ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:intnet]
    end
end
end
end