Vagrant.configure("2") do |config|
    # Общие настройки для всех машин
    config.vm.box = "ubuntu/jammy64"
  
    # Первая машина (client)
    config.vm.define "client" do |client|
      client.vm.hostname = "client"
      client.vm.network "private_network", ip: "192.168.11.150"
  
      client.vm.provider "virtualbox" do |vb|
        vb.name = "client"
        vb.memory = "1024"
        vb.cpus = 1
      end
  
      # Команды для машины client
      client.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt upgrade -y
     #   sudo apt install -y borgbackup
      SHELL
    end
  
    # Вторая машина (backup)
    config.vm.define "backup" do |backup|
      backup.vm.hostname = "backup"
      backup.vm.network "private_network", ip: "192.168.11.160"
  
      backup.vm.provider "virtualbox" do |vb|
        vb.name = "backup"
        vb.memory = "2048"
        vb.cpus = 2
      end
  
     backup.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt upgrade -y
#        sudo pvcreate /dev/sdb
#        sudo vgcreate backup /dev/sdb
#        sudo lvcreate -l 100%FREE -n borgbackup backup
#        mkdir /var/backup
#        sudo mkfs.ext4 /dev/backup/borgbackup
#        echo '/dev/backup/borgbackup /var/backup ext4 defaults 0 0' | sudo tee -a /etc/fstab
#        sudo mount -a
      #  sudo apt install borgbackup
      SHELL
    end

end