Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  
    boxes = [
      { name: "web", ip: "192.168.56.10" },
      { name: "log", ip: "192.168.56.15" }
    ]
  
    boxes.each do |opts|
      config.vm.define opts[:name] do |vm_config|
        vm_config.vm.hostname = opts[:name]
        vm_config.vm.network "private_network", ip: opts[:ip]
  
        # Provisioning script
        vm_config.vm.provision "shell", inline: <<-SHELL
          apt update 
          apt upgrade -y
        SHELL
      end
    end
  end
  