MACHINES = {
  :inetRouter => {
    :box_name => "generic/centos7",
    :vm_name => "inetRouter",
    :net => [
      {adapter: 2,ip: "0.0.0.0",type: "private_network", virtualbox__intnet: "router-net", auto_config: false},
      {adapter: 3,ip: "0.0.0.1",type: "private_network", virtualbox__intnet: "router-net", auto_config: false},
      {adapter: 4,ip: "192.168.56.10", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :centralRouter => {
    :box_name => "generic/centos7",
    :vm_name => "centralRouter",
    :net => [
      {adapter: 2,ip: "0.0.0.0",type: "private_network", virtualbox__intnet: "router-net", auto_config: false},
      {adapter: 3,ip: "0.0.0.0",type: "private_network", virtualbox__intnet: "router-net", auto_config: false},
      {adapter: 4,ip: "192.168.255.9", type: "private_network", netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
      {adapter: 5,ip: "192.168.56.11", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :office1Router => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "office1Router",
    :net => [
      {ip: "192.168.255.10", type: "private_network", netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
      {ip: "192.168.56.20", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :testClient1 => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "testClient1",
    :net => [
      {ip: "192.168.56.21", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :testServer1 => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "testServer1",
    :net => [
      {ip: "192.168.56.22", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :testClient2 => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "testClient2",
    :net => [
      {ip: "192.168.56.31", type: "private_network", netmask: "255.255.255.0"}
    ]
  },
  :testServer2 => {
    :box_name => "ubuntu/jammy64",
    :vm_name => "testServer2",
    :net => [
      {ip: "192.168.56.32", type: "private_network", netmask: "255.255.255.0"}
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      # Настройки для провайдера VirtualBox
      config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
      end

      # Настройки сетевых интерфейсов
      boxconfig[:net].each do |netconf|
        box.vm.network netconf[:type], ip: netconf[:ip], netmask: netconf[:netmask], virtualbox__intnet: netconf[:virtualbox__intnet]
      end

      # Провиженер для копирования SSH ключей
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end
end
