---
- name: Create VLAN
  hosts: all
  become: yes
  tasks:

  - name: Update on Debian-based
    shell: apt update -y 

  - name: Upgrade on Debian-based
    shell: apt upgrade -y 

  - name: Install software on Debian-based 
    apt:
      name:
        - traceroute
        - tcpdump
        - net-tools
      state: present

- name: set up vlan
  hosts: vlan1,vlan2
  become: yes
  tasks:
  - name: set up vlan2
    template:
      src: 50-vagrant.yaml.j2
      dest: /etc/netplan/50-vagrant.yaml 
      owner: root
      group: root
      mode: 0644

  - name: apply set up vlan2
    shell: netplan apply
    become: true

- name: set up bond0
  hosts: inetRouter,centralRouter
  become: yes
  tasks:
  - name: set up ifcfg-bond0
    template:
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644
  
  - name: set up eth1,eth2
    copy: 
      src: "{{ item }}" 
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - templates/ifcfg-eth1
      - templates/ifcfg-eth2
  - name: restart hosts for bond0
    reboot:
      reboot_timeout: 3600