Vagrant.configure("2") do |config|
  config.vm.define "deb11-test" do |srv|
    srv.vm.box = "bento/debian-12"
    srv.vm.box_version = "202401.31.0"
    srv.vm.provider :vmware_desktop do |vmware|
      vmware.gui = true
      vmware.cpus = 2
      vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
      vmware.ssh_info_public = true
      vmware.linked_clone = false
    end
  end
end  