---
- name:
  hosts: inetRouter
  become: yes
  tasks:

  - name: Restart sshd 
    service: 
      name: ufw
      state: stopped
      enabled: false

  - name: Set up NAT on inetRouter
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
      - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
    when: (ansible_hostname == "inetRouter")

  - name: Apply iptables rules with iptables-restore
    ansible.builtin.shell: |
      iptables-restore < /etc/iptables_rules.ipv4
    args:
      executable: /bin/bash
    become: yes  # Выполнение команды от имени суперпользователя


- name:
  hosts: routers
  become: yes
  tasks:

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"

- name:
  hosts: all
  become: yes
  tasks:

  - name: disable default route
    template: 
      src: 00-installer-config.yaml
      dest: /etc/netplan/00-installer-config.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname != "inetRouter") 

  - name: Install traceroute
    apt:
      name: traceroute
      state: present

  - name: add default gateway for centralRouter
    template: 
      src: "50-vagrant_{{ansible_hostname}}.yaml"
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644

#  - name: restart all hosts
#    reboot:
#      reboot_timeout: 600


