Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" 
    config.vm.define "server" do |server| 
    server.vm.hostname = "server" 
          server.vm.network "private_network", ip: "192.168.56.10" 
    end 
    
    config.vm.define "client" do |client| 
    client.vm.hostname = "client" 
    client.vm.network "private_network", ip: "192.168.56.20" 
    config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt upgrade -y
    SHELL
    end 
end
    