# Список машин
MACHINES = [
  {
    :name => "debian_vm",
    :hostname => "debian-vm",
    :ip => "192.168.33.10",
    :disks => [
      {
        :name => "sata1",
        :dfile => "/Users/admin/otus/9.GRUB/disks/sata1.vdi",
        :size => 10240,
        :port => 1
      }
  
    ],
    :memory => "1024",
    :cpus => 1
  }
]

Vagrant.configure("2") do |config|
  MACHINES.each do |machine|
    config.vm.define machine[:name] do |node|
      node.vm.box = "generic/centos7"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]

      # Создание виртуальных дисков
      machine[:disks].each do |disk|
        node.vm.provider :virtualbox do |vb|
          vb.customize ['createhd', '--filename', disk[:dfile], '--size', disk[:size].to_s]
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk[:port].to_s, '--device', '0', '--type', 'hdd', '--medium', disk[:dfile]]
        end
      end

      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:memory]
        vb.cpus = machine[:cpus]
      end

      # Проvisioning
      node.vm.provision "shell", inline: <<-SHELL
        # Установка LVM
        yum update
        yum install -y lvm2

        # Создание физических томов
        pvcreate /dev/sdb

        # Создание групп томов
        vgcreate vg_home /dev/sdb


        # Создание логических томов
        lvcreate -l 100%FREE -n lv_home vg_home
       
        # Форматирование и монтирование томов
        mkfs.ext4 /dev/vg_home/lv_home

        #mkdir -p /mnt/lv_home 
        mount /dev/vg_home/lv_home /mnt/
        cp -aR /home/* /mnt/
        rm -rf /home/*
        umount /mnt
        mount /dev/mapper/vg_home-lv_home /home/
        echo "`blkid | grep Home | awk '{print $2}'` \
        /home ext4 defaults 0 0" >> /etc/fstab



       
      SHELL
    end
  end
end
